config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'products#index'
    get 'index',                    to: 'products#index'
    get 'products/search',          to: 'products#search'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'

    resources :products,            only: [:show, :index]
    resources :categories,          only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :without_self, ->(product) { where.not(id: product.id) }

  def related_products
    Spree::Product.in_taxons(taxons).includes(variants_including_master: %i[images prices])
  end

  self.whitelisted_ransackable_attributes = %w[name slug description]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxons = Spree::Taxon.includes(:products)
    @taxonomies = Spree::Taxonomy.all
    option_type_of_color = Spree::OptionType.find_by(presentation: 'Color')
    @all_colors_of_products = option_type_of_color.option_values if option_type_of_color
    option_type_of_size = Spree::OptionType.find_by(presentation: 'Size')
    @all_size_of_products = option_type_of_size.option_values if option_type_of_size
    @products = params[:sort] ? sort_products(filter_products) : filter_products
    @selected = params[:sort]
  end

  def filter_by_color(color)
    products = Spree::Product.with_option_value('tshirt-color', color)
    products_filter_by_color = []
    products.each do |product|
      products_filter_by_color << product if product.taxons.pluck(:id).any? { |i| Spree::Taxon.find(params[:id]).self_and_descendants.pluck(:id).include?(i) }
    end
    @products_filter_by_color = products_filter_by_color
  end

  def filter_by_size(size)
    products = Spree::Product.with_option_value('tshirt-size', size)
    products_filter_by_size = []
    products.each do |product|
      products_filter_by_size << product if product.taxons.pluck(:id).any? { |i| Spree::Taxon.find(params[:id]).self_and_descendants.pluck(:id).include?(i) }
    end
    @products_filter_by_size = products_filter_by_size
  end

  def filter_products
    if params[:color]
      filter_by_color(params[:color])
      @products_filter_by_color
    elsif params[:size]
      filter_by_size(params[:size])
      @products_filter_by_size
    else
      Spree::Product.includes(variants_including_master: %i[images prices]).in_taxon(@taxon)
    end
  end

  def sort_products(products)
    if params[:sort] == 'NEW_PRODUCTS'
      products.sort_by(&:available_on).reverse
    elsif params[:sort] == 'LOW_PRICE'
      products.sort_by(&:price)
    elsif params[:sort] == 'HIGH_PRICE'
      products.sort_by(&:price).reverse
    elsif params[:sort] == 'OLD_PRODUCTS'
      products.sort_by(&:available_on)
    else
      products.sort_by(&:available_on).reverse
    end
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_NUMBER_OF_DISPLAYS = 4
  MAX_NUMBER_OF_DISPLAYS_NEW_ARRIVAL = 8

  def search
    @search_word = params[:searchWord]
    searched_products = Spree::Product.ransack(name_or_description_cont: params[:searchWord])
                                      .result.includes(variants_including_master: %i[images prices])
    @products = searched_products
  end

  def show
    @product = Spree::Product.friendly_id.find(params[:id])
    @images = @product.images
    @taxon_id = @product.taxons.first.id
    @related_products = @product.related_products.without_self(@product).distinct.sample(MAX_NUMBER_OF_DISPLAYS)
  end

  def index
    @new_arrival_products = Spree::Product.includes(
      variants_including_master: %i[images prices]
    ).order(available_on: :desc).limit(MAX_NUMBER_OF_DISPLAYS_NEW_ARRIVAL)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'BIGBAG Store'
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/helpers/potepan/categories_controller_helper.rb
module Potepan::CategoriesControllerHelper
  def filter_by_color(color)
    products = Spree::Product.with_option_value('tshirt-color', color)
    products_filter_by_color = []
    products.each do |product|
      products_filter_by_color << product if product.taxons.pluck(:id).any? { |i| Spree::Taxon.find(params[:id]).self_and_descendants.pluck(:id).include?(i) }
    end
    products_filter_by_color
  end

  def filter_by_size(size)
    products = Spree::Product.with_option_value('tshirt-size', size)
    products_filter_by_size = []
    products.each do |product|
      products_filter_by_size << product if product.taxons.pluck(:id).any? { |i| Spree::Taxon.find(params[:id]).self_and_descendants.pluck(:id).include?(i) }
    end
    products_filter_by_size
  end
end

app/views/potepan/categories/_filter_by_category.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= 'カテゴリーから探す' %></div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% taxonomies.each_with_index do |taxonomy, i| %>
          <li>
            <%= link_to "javascript:;", 'data-toggle': :collapse, 'aria-expanded': false, 'data-target': :"#category-#{i}" do %>
              <%= taxonomy.name %><i class="fa fa-plus"></i>
            <% end %>
            <ul id="category-<%= i %>" class="collapse collapseItem">
              <% taxons_related_taxonomy = taxons.where(taxonomy_id: taxonomy.id) %>
              <% taxons_related_taxonomy.each do |taxon| %>
                <% if taxon.products.size > 0 %>
                  <li>
                    <%= link_to potepan_category_path(taxon.id) do %>
                      <i class="fa fa-caret-right" aria-hidden="true"></i>
                      <%= taxon.name %><span> (<%= taxon.products.count %>)</span>
                    <% end %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_filter_by_color.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <% if all_colors_of_products %>
        <% all_colors_of_products.each do |color| %>
          <li>
            <%= link_to potepan_category_path(taxon.id, color: color.name) do %>
              <%= color.name %><span>(<%= filter_by_color(color.name).size %>)</span>
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/categories/_filter_by_size.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <% if all_size_of_products %>
        <% all_size_of_products.each do |size| %>
          <li>
            <%= link_to potepan_category_path(taxon.id, size: size.name) do %>
              <%= size.name %><span>(<%= filter_by_size(size.name).size %>)</span>
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/categories/_product_grid.html.erb
<% products.each do |product| %>
  <div class="col-sm-4 col-xs-12">
    <div class="productBox">
      <%= link_to potepan_product_path(product.id) do %>
        <div class="productImage clearfix">
          <%= image_tag(product.images.first ? product.images.first.url(:product) : Spree::Image.new.url(:product)) %>
        </div>
        <div class="productCaption clearfix">
          <h5><%= product.name %></h5>
          <h3><%= product.display_price%></h3>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/potepan/categories/show.html.erb
<%= provide :title, @taxon.name %>
<div class="main-wrapper">
  <%= render 'shared/header' %>
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2><%= @taxon.name %></h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li>
              <%= link_to 'Home', potepan_index_path %>
            </li>
            <li>
              <%= link_to 'Shop', '#' %>
            </li>
            <li class="active">
              <%= @taxon.name %>
            </li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <section class="mainContent clearfix productsContent">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
          <%= render 'filter_by_category', taxons: @taxons, taxonomies: @taxonomies %>
          <%= render 'filter_by_color', taxon: @taxon, all_colors_of_products: @all_colors_of_products %>
          <%= render 'filter_by_size', taxon: @taxon, all_size_of_products: @all_size_of_products %>
        </div>
        <div class="col-md-9 col-sm-8 col-xs-12">
          <div class="row filterArea">
            <div class="col-xs-6">
              <form id="submit_form", method="get", action="<%= potepan_category_path(@taxon.id)%>">
                <select name="sort" id="guiest_id1" class="select-drop">
                  <option value="NEW_PRODUCTS" <%= selected="selected" if @selected == "NEW_PRODUCTS" %>>新着順</option>
                  <option value="LOW_PRICE" <%= selected="selected" if @selected == "LOW_PRICE" %>>安い順</option>
                  <option value="HIGH_PRICE" <%= selected="selected" if @selected == "HIGH_PRICE" %>>高い順</option>
                  <option value="OLD_PEODUCTS" <%= selected="selected" if @selected == "OLD_PRODUCTS" %>>古い順</option>
                </select>
              </form>
            </div>
            <div class="col-xs-6">
              <div class="btn-group pull-right" role="group">
                <button type="button" class="btn btn-default active" onclick="window.location.href=<%= potepan_category_path(@taxon) %>">
                  <i class="fa fa-th" aria-hidden="true"></i>
                  <span>Grid</span></button>
                <button type="button" class="btn btn-default" onclick="window.location.href='#'">
                  <i class="fa fa-th-list" aria-hidden="true"></i>
                  <span>List</span></button>
              </div>
            </div>
          </div>
          <div class="row">
            <%= render 'product_grid', products: @products %>
          </div>
        </div>
      </div>
    </div>
  </section>
  <%= render 'shared/partners_logo_slider' %>
</div>

app/views/potepan/products/_product_grid.html.erb
<% products.each do |product| %>
  <div class="col-sm-3 col-xs-12">
    <div class="productBox">
      <%= link_to potepan_product_path(product.id) do %>
        <div class="productImage clearfix">
          <%= image_tag(product.images.first ? product.images.first.url(:product) : Spree::Image.new.url(:product)) %>
        </div>
        <div class="productCaption clearfix">
          <h5><%= product.name %></h5>
          <h3><%= product.display_price%></h3>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/potepan/products/search.html.erb
<%= provide :title, "Results by Search #{@search_word}" %>
<div class="main-wrapper">
  <%= render 'shared/header' %>
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2><%= @search_word %></h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li>
              <%= link_to 'Home', potepan_index_path %>
            </li>
            <li>
              <%= link_to 'Shop', '#' %>
            </li>
            <li class="active">
              <%= @search_word %>
            </li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <section class="mainContent clearfix productsContent">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="row">
            <%= render 'product_grid', products: @products %>
          </div>
        </div>
      </div>
    </div>
  </section>
  <%= render 'shared/partners_logo_slider' %>
</div>

app/views/potepan/products/show.html.erb
<%= provide :title, @product.name %>
<div class="main-wrapper">
  <%= render 'shared/header' %>
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2><%= @product.name %></h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li>
              <%= link_to 'Home', potepan_index_path %>
            </li>
            <li class="active">
              <%= @product.name %>
            </li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <section class="mainContent clearfix">
    <div class="container">
      <div class="row singleProduct">
        <div class="col-xs-12">
          <div class="media">
            <div class="media-left productSlider">
              <div id="carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <% @images.each_with_index do |image, i| %>
                    <div class="item <%= "active" if i== 0 %>" data-thumb="<%= i %>">
                      <%= image_tag(image.url(:large)) %>
                    </div>
                  <% end %>
                </div>
              </div>
              <div class="clearfix">
                <div id="thumbcarousel" class="carousel slide" data-interval="false">
                  <div class="carousel-inner">
                    <% @images.each_with_index do |image, i| %>
                        <div data-target="#carousel" data-slide-to="<%= i %>" class="thumb">
                          <%= image_tag(image.url(:product)) %>
                        </div>
                    <% end %>
                  </div>
                  <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                  </a>
                  <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                  </a>
                </div>
              </div>
            </div>
            <div class="media-body">
              <ul class="list-inline">
                <li>
                  <%= link_to potepan_category_path(@taxon_id) do %>
                    <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                  <% end %>
                </li>
              </ul>
              <h2><%= @product.name %></h2>
              <h3><%= @product.display_price %></h3>
              <p><%= @product.description %></p>
              <span class="quick-drop">
                <select name="product_size" id="guiest_id3" class="select-drop">
                  <option value="S">S</option>
                  <option value="M">M</option>
                  <option value="L">L</option>
                  <option value="XL">XL</option>
                </select>
              </span>
              <span class="quick-drop resizeWidth">
                <select name="number_of_orders" id="guiest_id4" class="select-drop">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                </select>
              </span>
              <div class="btn-area">
                <%= link_to "#", class: "btn btn-primary btn-block" do %>
                  カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <%= render 'shared/related_products', related_products: @related_products %>
    </div>
  </section>
</div>

app/views/potepan/sample/index.html.erb
<div class="main-wrapper">
  <!-- HEADER -->
  <div class="header clearfix">
    <!-- TOPBAR -->
    <div class="topBar">
      <div class="container">
        <div class="row">
          <div class="col-md-6 hidden-sm hidden-xs">
            <ul class="list-inline">
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            </ul>
          </div>
          <div class="col-md-6 col-xs-12">
            <ul class="list-inline pull-right">
              <li class="dropdown searchBox">
                <%= link_to "javascript:void(0)", class: "dropdown-toggle", 'data-toggle': :dropdown do %>
                  <i class="fa fa-search"></i>
                <% end %>
                <ul class="dropdown-menu dropdown-menu-right">
                  <%= form_with url: "#", id: "form01", method: :get, local: true do |form| %>
                    <li>
                      <span class="input-group">
                        <%= form.text_field "searchWord", class: "form-control", placeholder: "Search…", 'aria-describedby': "basic-addon2" %>
                        <span type="btn" class="input-group-addon addPointer" id="basic-addon2">検索</span>
                     </span>
                   </li>
                 <% end %>
                </ul>
              </li>
              <li class="dropdown">
                <%= link_to potepan_cart_page_path, class: "dropdown-toggle", 'data-toggle': :disabled do %>
                  <i class="fa fa-shopping-cart"></i>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- NAVBAR -->
    <nav class="navbar navbar-main navbar-default" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="javascript:void(0)"><%= image_tag("logo.png") %></a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><%= link_to 'Home', "javascript:void(0)" %></li>
            <li class="dropdown megaDropMenu">
              <%= link_to 'Shop', "javascript:void(0)", class: "dropdown-toggle", 'data-toggle': :dropdown, 'data-hover': :dropdown, 'data-delay': 300, 'data-close-others': true, 'aria-expanded': false %>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
  </div>
  <!-- BANNER -->
  <div class="bannercontainer">
    <div class="fullscreenbanner-container">
      <div class="fullscreenbanner">
        <ul>
          <li>
            <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg1", data:{bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat"}) %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix">
    <div class="container">
      <div class="row featuredCollection">
        <div class="col-xs-12">
          <div class="page-header">
            <h4>人気カテゴリー</h4>
          </div>
        </div>
        <div class="col-sm-4 col-xs-12">
          <div class="thumbnail" onclick="location.href='#';">
            <div class="imageWrapper">
              <%= image_tag("home/featured-collection/featured-collection-01.jpg", :alt => "feature-collection-image") %>
              <div class="masking"><%= link_to 'View Shirts', '#', class: "btn viewBtn" %></div>
            </div>
            <div class="caption">
              <h4>Shirts</h4>
            </div>
          </div>
        </div>
        <div class="col-sm-4 col-xs-12">
          <div class="thumbnail" onclick="location.href='#';">
            <div class="imageWrapper">
              <%= image_tag("home/featured-collection/featured-collection-02.jpg", :alt => "feature-collection-image") %>
              <div class="masking"><%= link_to 'View Bags', "#", class: "btn viewBtn" %></div>
            </div>
            <div class="caption">
              <h4>Bags</h4>
            </div>
          </div>
        </div>
        <div class="col-sm-4 col-xs-12">
          <div class="thumbnail" onclick="#';">
            <div class="imageWrapper">
              <%= image_tag("home/featured-collection/featured-collection-03.jpg", :alt => "feature-collection-image") %>
              <div class="masking"><%= link_to 'View Denim', "#", class: "btn viewBtn" %></div>
            </div>
            <div class="caption">
              <h4>Denim</h4>
            </div>
          </div>
        </div>
      </div>
      <div class="row featuredProducts">
        <div class="col-xs-12">
          <div class="page-header">
            <h4>新着商品</h4>
          </div>
        </div>
        <div class="col-xs-12">
          <div class="owl-carousel featuredProductsSlider">
            <div class="slide">
              <div class="productImage clearfix">
                <%= image_tag("home/featured-product/product-01.jpg", :alt => "featured-product-img") %>
              </div>
              <div class="productCaption clearfix">
                <%= link_to "#" do %>
                  <h5>Mauris efficitur</h5>
                <% end %>
                <h3>199円</h3>
              </div>
            </div>
            <div class="slide">
              <div class="productImage">
                <%= image_tag("home/featured-product/product-02.jpg", :alt => "featured-product-img") %>
              </div>
              <div class="productCaption">
                <%= link_to "#" do %>
                  <h5>Nulla facilisi</h5>
                <% end %>
                <h3>149円</h3>
              </div>
            </div>
            <div class="slide">
              <div class="productImage">
                <%= image_tag("home/featured-product/product-03.jpg", :alt => "featured-product-img") %>
              </div>
              <div class="productCaption">
                <%= link_to "#" do %>
                  <h5>Praesent dui felis</h5>
                <% end %>
                <h3>79円</h3>
              </div>
            </div>
            <div class="slide">
              <div class="productImage">
                <%= image_tag("home/featured-product/product-04.jpg", :alt => "featured-product-img") %>
              </div>
              <div class="productCaption">
                <%= link_to "#" do %>
                  <h5>Cras eu faucibus</h5>
                <% end %>
                <h3>109円</h3>
              </div>
            </div>
            <div class="slide">
              <div class="productImage">
                <%= image_tag("home/featured-product/product-05.jpg", :alt => "featured-product-img") %>
              </div>
              <div class="productCaption">
                <%= link_to "#" do %>
                  <h5>Mauris lobortis augue</h5>
                <% end %>
                <h3>199円</h3>
              </div>
            </div>
            <div class="slide">
              <div class="productImage">
                <%= image_tag("home/featured-product/product-06.jpg", :alt => "featured-product-img") %>
              </div>
              <div class="productCaption">
                <%= link_to "#" do %>
                  <h5>Suspendisse suscipit</h5>
                <% end %>
               <h3>149円</h3>
              </div>
            </div>
            <div class="slide">
              <div class="productImage">
                <%= image_tag("home/featured-product/product-07.jpg", :alt => "featured-product-img") %>
              </div>
              <div class="productCaption">
                <%= link_to "#" do %>
                  <h5>Praesent a augue</h5>
                <% end %>
                <h3>79円</h3>
              </div>
            </div>
            <div class="slide">
              <div class="productImage">
                <%= image_tag("home/featured-product/product-09.jpg", :alt => "featured-product-img") %>
              </div>
              <div class="productCaption">
                <%= link_to "#" do %>
                  <h5>Cras vel augue</h5>
                <% end %>
                <h3>109円</h3>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- LIGHT SECTION -->
  <section class="lightSection clearfix">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="owl-carousel partnersLogoSlider">
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("home/partners/partner-01.png", :alt => "partner-img") %>
              </div>
            </div>
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("home/partners/partner-02.png", :alt => "partner-img") %>
              </div>
            </div>
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("home/partners/partner-03.png", :alt => "partner-img") %>
              </div>
            </div>
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("home/partners/partner-04.png", :alt => "partner-img") %>
              </div>
            </div>
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("home/partners/partner-05.png", :alt => "partner-img") %>
              </div>
            </div>
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("home/partners/partner-01.png", :alt => "partner-img") %>
              </div>
            </div>
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("home/partners/partner-02.png", :alt => "partner-img") %>
              </div>
            </div>
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("home/partners/partner-03.png", :alt => "partner-img") %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-main navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("img/logo.png", :alt => ""), potepan_index_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', potepan_index_path %></li>
        <li class="dropdown megaDropMenu active">
          <%= link_to 'Shop', "javascript:void(0)", class: "dropdown-toggle", 'data-toggle': :dropdown, 'data-hover': :dropdown, 'data-delay': 300, 'data-close-others': true, 'aria-expanded': false  %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
</nav>